apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: super-saiyan-app-2.0
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: super-saiyan-app-v2
        version: "3.0"
    spec:
      containers: 
        - name: super-saiyan-app-v2
          image: brudnyhenry/super-saiyan-app:v2
          ports:
            - name: http
              containerPort: 8080
