apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: super-saiyan-app-1.0
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: super-saiyan-app
        version: "1.0"
    spec:
      containers: 
        - name: super-saiyan-app
          image: brudnyhenry/super-saiyan-app:v1
          ports:
            - name: http
              containerPort: 8080