apiVersion: v1
kind: Service
metadata: 
  name: super-saiyan-app
  labels: 
    name: super-saiyan-app
spec:
  ports:
    - name: http
      protocol: "TCP"
      port: 8080
      targetPort: 8080
  selector: 
    name: super-saiyan-app
    version: "1.10"
  type: LoadBalancer
